MYSQL_ADDON_DB="brtydnjlnias0ceirmt3"
MYSQL_ADDON_HOST="brtydnjlnias0ceirmt3-mysql.services.clever-cloud.com"
MYSQL_ADDON_PASSWORD="MeJe34Fi8UOAVfTBsrJs"
MYSQL_ADDON_PORT="3306"
MYSQL_ADDON_URI="mysql://ujl58k8dmlsjtfzm:MeJe34Fi8UOAVfTBsrJs@brtydnjlnias0ceirmt3-mysql.services.clever-cloud.com:3306/brtydnjlnias0ceirmt3"
MYSQL_ADDON_USER="ujl58k8dmlsjtfzm"
MYSQL_ADDON_VERSION="8.0"